services:
  api-venda-test:
    container_name: api-venda-test
    build:
      context: .docker/node/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - '3006:3006'
      - '7006:7006'
    volumes:
      - .:/home/node/app
    depends_on:
      db-venda-test:
        condition: service_healthy

  db-venda-test:
    container_name: db-venda-test
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5006
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-venda-test
    ports:
      - '5005:5005'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5006']
      interval: 5s
      timeout: 5s
      retries: 5